name: CustomSMP
version: '${project.version}'
main: me.lunafy.customsmp.CustomSMP
api-version: '1.20'
softdepend:
  - DecentHolograms
commands:
  getstat:
    usage: /<command>
    description: lol
  haunt:
    usage: /<command>
    description: hauntee